version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trend-blend:latest
    container_name: trend-blend
    restart: always
    ports:
      - "3000:8080"
